import SwiftUI
import CoreData

// MARK: - Brew Editor

struct BrewEditor: View {
    @Environment(\.managedObjectContext) private var viewContext

    @StateObject private var viewModel: BrewEditorViewModel

    @FetchRequest(
        sortDescriptors: [NSSortDescriptor(keyPath: \Coffee.name, ascending: true)],
        animation: .default
    )
    private var coffees: FetchedResults<Coffee>

    init(startingPoint: BrewStartingPoint = .template(.v60), context: NSManagedObjectContext? = nil) {
        let ctx = context ?? PersistenceController.shared.container.viewContext
        self._viewModel = StateObject(wrappedValue: BrewEditorViewModel(startingPoint: startingPoint, context: ctx))
    }

    var body: some View {
        FixedBottomLayout(
            content: {
                VStack(spacing: 28) {
                    PageTitleH2("New Brew", subtitle: "Set up your next experiment")
                    nameSection
                    coffeeSection
                    stagesSection
                    paramsSection
                }
            },
            actions: {
                StandardButton(
                    title: "Save & Brew",
                    iconName: "checkmark.circle.fill",
                    action: {
                        viewModel.validateAndSave()
                    },
                    style: .primary
                )
                .opacity(viewModel.selectedCoffee == nil ? 0.6 : 1.0)
                .disabled(viewModel.selectedCoffee == nil || viewModel.isSaving)
            }
        )
        .alert(isPresented: $viewModel.showValidationAlert) {
            Alert(
                title: Text("Cannot Save"),
                message: Text(viewModel.validationMessage),
                dismissButton: .default(Text("OK"))
            )
        }
        .overlay {
            if viewModel.isSaving {
                ProgressView()
                    .progressViewStyle(CircularProgressViewStyle(tint: BrewerColors.caramel))
                    .scaleEffect(1.5)
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
                    .background(Color.black.opacity(0.2))
            }
        }
    }

    // MARK: - Name Section

    private var nameSection: some View {
        TextField(viewModel.autoGeneratedName, text: $viewModel.formData.name)
            .font(.system(size: 17, weight: .medium))
            .foregroundColor(BrewerColors.textPrimary)
            .padding(.horizontal, 16)
            .padding(.vertical, 14)
            .background(BrewerColors.cardBackground)
            .cornerRadius(12)
            .padding(.horizontal, 20)
    }

    // MARK: - Coffee Section

    private var coffeeSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 8) {
                SVGIcon("coffee.bag", size: 18, color: BrewerColors.caramel)
                SecondaryHeader(title: "Coffee")
            }
            .padding(.horizontal, 20)

            Menu {
                Button("None") { viewModel.selectedCoffee = nil }
                if !coffees.isEmpty { Divider() }
                ForEach(coffees) { coffee in
                    Button(coffee.displayName) {
                        viewModel.selectedCoffee = coffee
                    }
                }
            } label: {
                HStack {
                    Text(viewModel.selectedCoffee?.displayName ?? "Select Coffee")
                        .font(.system(size: 15))
                        .foregroundColor(
                            viewModel.selectedCoffee == nil
                                ? BrewerColors.textSecondary
                                : BrewerColors.textPrimary
                        )
                    Spacer()
                    Image(systemName: "chevron.up.chevron.down")
                        .font(.system(size: 11, weight: .medium))
                        .foregroundColor(BrewerColors.textSecondary)
                }
                .padding(.horizontal, 16)
                .padding(.vertical, 14)
                .background(BrewerColors.cardBackground)
                .cornerRadius(12)
                .padding(.horizontal, 20)
            }
        }
    }

    // MARK: - Stages Section

    private var stagesSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 8) {
                SVGIcon("drop.fast", size: 18, color: BrewerColors.caramel)
                SecondaryHeader(title: "Pour Pattern")
                Spacer()
                Text("\(viewModel.totalWater)ml total")
                    .font(.system(size: 12, weight: .medium))
                    .foregroundColor(BrewerColors.textSecondary)
                    .padding(.trailing, 20)
            }
            .padding(.horizontal, 20)

            VStack(spacing: 0) {
                ForEach(Array(viewModel.formData.stages.enumerated()), id: \.element.id) { index, stage in
                    VStack(spacing: 0) {
                        StageRowView(
                            stage: stage,
                            onToggleType: {
                                viewModel.toggleStageType(at: index)
                            },
                            onUpdateWater: { amount in
                                viewModel.updateStageWater(at: index, amount: amount)
                            },
                            onDelete: {
                                viewModel.deleteStage(at: IndexSet(integer: index))
                            }
                        )

                        if index < viewModel.formData.stages.count - 1 {
                            CustomDivider()
                                .padding(.horizontal, 16)
                        }
                    }
                }

                CustomDivider()
                    .padding(.horizontal, 16)

                Button(action: { viewModel.addStage() }) {
                    HStack(spacing: 8) {
                        Image(systemName: "plus.circle.fill")
                            .font(.system(size: 15))
                            .foregroundColor(BrewerColors.caramel)
                        Text("Add Pour")
                            .font(.system(size: 15, weight: .medium))
                            .foregroundColor(BrewerColors.caramel)
                    }
                    .frame(maxWidth: .infinity)
                    .padding(.vertical, 14)
                }
                .buttonStyle(.plain)
                .padding(.horizontal, 16)
            }
            .background(BrewerColors.cardBackground)
            .cornerRadius(12)
            .padding(.horizontal, 20)
        }
    }

    // MARK: - Compact Params Section

    private var paramsSection: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(spacing: 8) {
                SVGIcon("parameters", size: 18, color: BrewerColors.caramel)
                SecondaryHeader(title: "Parameters")
            }
            .padding(.horizontal, 20)

            ScrollView(.horizontal, showsIndicators: false) {
                HStack(spacing: 10) {
                    BrewParamCell(
                        label: "Grind",
                        value: formatDouble(viewModel.formData.grindSize),
                        unit: "",
                        onCommit: { text in
                            if let v = Double(text), v > 0 {
                                viewModel.formData.grindSize = v
                            }
                        }
                    )

                    BrewParamCell(
                        label: "Dose",
                        value: "\(viewModel.formData.grams)",
                        unit: "g",
                        onCommit: { text in
                            if let v = Int16(text), v > 0 {
                                viewModel.formData.grams = v
                            }
                        }
                    )

                    BrewParamCell(
                        label: "Temp",
                        value: formatDouble(viewModel.formData.temperature),
                        unit: "°C",
                        onCommit: { text in
                            if let v = Double(text), v > 0 {
                                viewModel.formData.temperature = v
                            }
                        }
                    )

                    BrewMethodCell(
                        method: viewModel.formData.brewMethod,
                        onToggle: {
                            viewModel.formData.brewMethod =
                                viewModel.formData.brewMethod == .v60 ? .oreaV4 : .v60
                        }
                    )
                }
                .padding(.horizontal, 20)
                .padding(.vertical, 2)
            }
        }
    }

    // MARK: - Helpers

    private func formatDouble(_ value: Double) -> String {
        value == value.rounded() ? "\(Int(value))" : String(format: "%.1f", value)
    }
}

// MARK: - Brew Param Cell

private struct BrewParamCell: View {
    let label: String
    let value: String
    let unit: String
    let onCommit: (String) -> Void

    @State private var isEditing = false
    @State private var editText = ""
    @FocusState private var isFocused: Bool

    var body: some View {
        VStack(spacing: 3) {
            Text(label)
                .font(.system(size: 10, weight: .medium))
                .foregroundColor(BrewerColors.textSecondary)

            if isEditing {
                HStack(spacing: 1) {
                    TextField("", text: $editText)
                        .keyboardType(.decimalPad)
                        .font(.system(size: 15, weight: .semibold))
                        .foregroundColor(BrewerColors.textPrimary)
                        .multilineTextAlignment(.center)
                        .frame(width: 44)
                        .focused($isFocused)
                        .onSubmit { commitEdit() }
                        .onChange(of: isFocused) { _, focused in
                            if !focused { commitEdit() }
                        }
                    if !unit.isEmpty {
                        Text(unit)
                            .font(.system(size: 11))
                            .foregroundColor(BrewerColors.textSecondary)
                    }
                }
                .onAppear {
                    editText = value
                    isFocused = true
                }
            } else {
                Text(value + unit)
                    .font(.system(size: 15, weight: .semibold))
                    .foregroundColor(BrewerColors.textPrimary)
            }
        }
        .frame(minWidth: 64)
        .padding(.horizontal, 14)
        .padding(.vertical, 10)
        .background(
            RoundedRectangle(cornerRadius: 10)
                .fill(isEditing ? BrewerColors.caramel.opacity(0.15) : BrewerColors.cardBackground)
        )
        .onTapGesture {
            if !isEditing {
                editText = value
                isEditing = true
            }
        }
    }

    private func commitEdit() {
        onCommit(editText)
        isEditing = false
    }
}

// MARK: - Brew Method Cell

private struct BrewMethodCell: View {
    let method: BrewMethod
    let onToggle: () -> Void

    var body: some View {
        Button(action: onToggle) {
            VStack(spacing: 3) {
                Text("Method")
                    .font(.system(size: 10, weight: .medium))
                    .foregroundColor(BrewerColors.textSecondary)
                Text(method.displayName)
                    .font(.system(size: 15, weight: .semibold))
                    .foregroundColor(BrewerColors.textPrimary)
            }
            .frame(minWidth: 64)
            .padding(.horizontal, 14)
            .padding(.vertical, 10)
            .background(
                RoundedRectangle(cornerRadius: 10)
                    .fill(BrewerColors.cardBackground)
            )
        }
        .buttonStyle(.plain)
    }
}

// MARK: - Preview

#Preview {
    GlobalBackground {
        NavigationStack {
            BrewEditor(context: PersistenceController.preview.container.viewContext)
                .environment(\.managedObjectContext, PersistenceController.preview.container.viewContext)
        }
    }
}
