import SwiftUI
import CoreData

// MARK: - Brew Starting Point

enum BrewStartingPoint {
    case template(BrewMethod)
    case cloneFromBrew(Brew)
}

// MARK: - Brew Editor View Model

@MainActor
class BrewEditorViewModel: ObservableObject {

    // MARK: - Published State
    @Published var formData: BrewFormData
    @Published var selectedCoffee: Coffee?
    @Published var showValidationAlert = false
    @Published var validationMessage = ""
    @Published var isSaving = false

    private let viewContext: NSManagedObjectContext

    // MARK: - Computed Properties

    var totalWater: Int16 {
        Int16(min(Int(Int16.max), formData.stages.reduce(0) { $0 + Int($1.waterAmount) }))
    }

    var autoGeneratedName: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        let dateStr = formatter.string(from: Date())
        if let coffee = selectedCoffee {
            return "\(coffee.displayName) — \(dateStr)"
        }
        return "Brew — \(dateStr)"
    }

    // MARK: - Init

    init(startingPoint: BrewStartingPoint = .template(.v60), context: NSManagedObjectContext) {
        self.viewContext = context
        switch startingPoint {
        case .template(let method):
            self.formData = Self.makeFormData(for: method)
        case .cloneFromBrew(let brew):
            self.formData = BrewFormData(cloning: brew)
            self.selectedCoffee = brew.coffee
        }
    }

    // MARK: - Stage Management

    func addStage() {
        let nextIndex = Int16(formData.stages.count)
        formData.stages.append(StageFormData(type: .slow, waterAmount: 60, orderIndex: nextIndex))
    }

    func deleteStage(at offsets: IndexSet) {
        guard offsets.allSatisfy({ $0 < formData.stages.count }) else { return }
        formData.stages.remove(atOffsets: offsets)
        reindexStages()
    }

    func toggleStageType(at index: Int) {
        guard index < formData.stages.count else { return }
        formData.stages[index].type = formData.stages[index].type == .fast ? .slow : .fast
    }

    func updateStageWater(at index: Int, amount: Int16) {
        guard index < formData.stages.count else { return }
        formData.stages[index].waterAmount = amount
    }

    // MARK: - Validation & Save

    @discardableResult
    func validateAndSave() -> Bool {
        guard selectedCoffee != nil else {
            validationMessage = "Please select a coffee to continue"
            showValidationAlert = true
            return false
        }
        guard !formData.stages.isEmpty, totalWater > 0 else {
            validationMessage = "Add at least one pour stage"
            showValidationAlert = true
            return false
        }
        return saveBrew()
    }

    // MARK: - Private

    private static func makeFormData(for method: BrewMethod) -> BrewFormData {
        var data = BrewFormData(brewMethod: method)
        data.grindSize = 31.5
        data.stages = defaultStages(for: method)
        return data
    }

    private static func defaultStages(for method: BrewMethod) -> [StageFormData] {
        switch method {
        case .v60:
            // fast 80ml + slow 120ml + slow 106ml = 306ml (18g × 17 ratio)
            return [
                StageFormData(type: .fast, waterAmount: 80, orderIndex: 0),
                StageFormData(type: .slow, waterAmount: 120, orderIndex: 1),
                StageFormData(type: .slow, waterAmount: 106, orderIndex: 2)
            ]
        case .oreaV4:
            // fast 80ml + slow 70ml + fast 80ml + slow 76ml = 306ml (18g × 17 ratio)
            return [
                StageFormData(type: .fast, waterAmount: 80, orderIndex: 0),
                StageFormData(type: .slow, waterAmount: 70, orderIndex: 1),
                StageFormData(type: .fast, waterAmount: 80, orderIndex: 2),
                StageFormData(type: .slow, waterAmount: 76, orderIndex: 3)
            ]
        }
    }

    private func reindexStages() {
        for i in formData.stages.indices {
            formData.stages[i].orderIndex = Int16(i)
        }
    }

    private func saveBrew() -> Bool {
        isSaving = true

        let brew = Brew(context: viewContext)
        brew.id = UUID()
        brew.date = Date()
        brew.brewMethod = formData.brewMethod.rawValue
        brew.grams = formData.grams
        brew.ratio = formData.ratio
        brew.temperature = formData.temperature
        brew.grindSize = formData.grindSize
        brew.waterAmount = totalWater
        brew.coffee = selectedCoffee
        brew.roasterName = selectedCoffee?.roaster?.name

        let trimmedName = formData.name.trimmingCharacters(in: .whitespacesAndNewlines)
        brew.name = trimmedName.isEmpty ? autoGeneratedName : trimmedName

        let trimmedNotes = formData.notes.trimmingCharacters(in: .whitespacesAndNewlines)
        brew.notes = trimmedNotes.isEmpty ? nil : trimmedNotes

        for stageData in formData.stages {
            let stage = Stage(context: viewContext)
            stage.id = UUID()
            stage.type = stageData.type.id
            stage.waterAmount = stageData.waterAmount
            stage.orderIndex = stageData.orderIndex
            stage.brew = brew
        }

        do {
            try viewContext.save()
            isSaving = false
            NotificationService.scheduleBrewRatingReminder(brewID: brew.id!)
            NotificationCenter.default.post(name: .brewSaved, object: nil)
            return true
        } catch {
            print("Failed to save brew: \(error)")
            isSaving = false
            validationMessage = "Failed to save brew"
            showValidationAlert = true
            return false
        }
    }
}

// MARK: - Notification Names

extension Notification.Name {
    static let brewSaved = Notification.Name("brewSaved")
}
